apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-deployment
  namespace: app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: myapp-container
        image: containerregistrydemo123.azurecr.io/containerregistrydemo123/phpproject
        ports:
        - containerPort: 80
      imagePullSecrets:
      - name: acr-auth

---

apiVersion: v1
kind: Service
metadata:
  name: myapp-service
  namespace: app
spec:
  type: NodePort
  selector:
    app: myapp
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30002
